config/routes.rb
BaseApp::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "pages/index"

  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do

    resources :users

  end

  root :to => "pages#index"

end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :users

  def self.admin
    find_or_create_by(:name => "admin")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable

  has_and_belongs_to_many :roles

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  def make_admin
    self.roles << Role.admin
  end

  def revoke_admin
    self.roles.delete(Role.admin)
  end

  def admin?
    role?(:admin)
  end

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['info']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_filter :require_admin
  layout "admin"

  def index
  end

  protected

  def require_admin
    unless current_user.try(:admin?)
      render404 and return false
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  helper_method :sort_column, :sort_direction, :search_params

  before_filter :find_user, :only => [:edit, :update, :show, :destroy]

  def index
    @q = User.search(params[:q])
    search_relation = @q.result
    @users = search_relation.order(sort_column + " " + sort_direction).references(:user).page params[:page]
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user].permit(:email))
      redirect_to admin_users_path, :notice => "User successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, :notice => "User deleted."
  end

  protected

  def find_user
    @user = User.find(params[:id])
  end

  private

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "email"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def search_params
    { :search => params[:search] }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def render404
    render :file => File.join(Rails.root, 'public', '404.html'), :status => 404, :layout => false
    return true
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, { :sort => column, :direction => direction }, { :class => css_class }
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/base/index.html.erb
<div class="page-title">
  <h2>Admin dashboard</h2>
</div>

app/views/admin/users/edit.html.erb
<div class="page-header">
  <h2>Editing user <%= @user.email %></h2>
</div>

<%= form_for [:admin, @user], :html => { :class => "form-horizontal", :role => "form" } do |f| -%>

  <%= f.error_messages %>

  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.email_field :email, :type => :email, :class => "form-control", :placeholder => "Enter new email" %>
    </div>
  </div>

  </br>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <%= f.submit "Update", :class => "btn btn-default" %>
    </div>
  </div>

<% end -%>

app/views/admin/users/index.html.erb
<div class="page-header">
  <h1>Users</h1>
</div>

<%= search_form_for @q, :url => admin_users_path, :html => { :method => :get, :class => "well form-inline" } do |f| %>
  <div class="form-group">
    <%= f.text_field :email_cont, :type => "search", :class => "form-control", :placeholder => "Search by email" %>
  </div>

  <%= f.submit "Search", :class => "btn btn-default" %>
<% end %>

<table class="sortable table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th><%= sortable "id", "ID" %></th>
      <th><%= sortable "email" %></th>
      <th><%= sortable "created_at", "Signed up" %></th>
      <th><%= sortable "sign_in_count", "Times signed in" %></th>
      <th><%= sortable "last_sign_in_at", "Last signed in" %></th>
      <th><%= sortable "last_sign_in_ip", "Last sign in IP" %></th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="user">
        <td><%= link_to(user.id, admin_user_path(user)) %></td>
        <td><%= link_to(user.email, admin_user_path(user)) %></td>
        <td><%= l( user.created_at, :format => :short) %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= l( user.last_sign_in_at, :format => :long) %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), :data => { :confirm => 'Are you sure?' }, :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/admin/users/show.html.erb
<div class="page-header">
  <h2><%= @user.email %></h2>
</div>

<table class="table table-bordered">
  <tr>
    <td>ID</td>
    <td><%= @user.id %></td>
  </tr>

  <tr>
    <td>Email</td>
    <td><%= @user.email %></td>
  </tr>

  <tr>
  <td>Sign in count</td>
  <td><%= @user.sign_in_count %></td>
  </tr>

  <tr>
    <td>Last sign in at</td>
    <td><%= l( @user.last_sign_in_at, :format => :long ) %></td>
  </tr>

  <tr>
    <td>Last sign in IP</td>
    <td><%= @user.last_sign_in_ip %></td>
  </tr>

  <tr>
    <td>Created at</td>
    <td><%= l( @user.created_at, :format => :long ) %></td>
  </tr>

  <tr>
    <td>Updated at</td>
    <td><%= l( @user.updated_at, :format => :long ) %></td>
  </tr>

  <tr>
    <td>Actions</td>
    <td>
      <%= link_to("Edit", edit_admin_user_path(@user), :class => "btn btn-default") %>
      <%= link_to("Destroy", admin_user_path(@user), :data => { :confirm => 'Are you sure?' }, :method => :delete, :class => "btn btn-danger btn-xs") %>
    </td>
  </tr>
</table>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <title>Base Application - Admin Dashboard</title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= yield :head %>

  </head>

  <body>

    <%= render "layouts/admin/main_nav" %>

    <div class="container">

    <%= render "layouts/application/flash_messages" %>

      <%= yield %>

    </div>

  </body>

</html>

app/views/layouts/admin/_main_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#baseapp-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Base Application", admin_path, :class => "navbar-brand" %>
    </div>


    <div class="collapse navbar-collapse" id="baseapp-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to("Users", admin_users_path) %></li>
        <li><%= link_to("Exit →", root_path) %></li>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <title>Base Application</title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= yield :head %>

  </head>

  <body>

    <%= render "layouts/application/header" %>

    <div class="container-fluid">

      <%= render "layouts/application/flash_messages" %>

      <%= yield %>

    </div>

  </body>

</html>

app/views/layouts/application/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<% if alert %>
  <div class="alert alert-error"><p><%= alert %></p></div>
<% end %>

app/views/layouts/application/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#baseapp-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Base Application", root_path, :class => "navbar-brand" %>
    </div>


    <div class="collapse navbar-collapse" id="baseapp-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Account settings", edit_user_registration_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Admin", admin_path %></li>
          <% end %>
          <li><%= link_to "Sign out", destroy_user_session_path %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
        <% end -%>
      </ul>
    </div>

  </div>
</nav>

app/views/pages/index.html.erb
<h1>Welcome <%= current_user.email if current_user %></h1>